//const FROM_EMAIL = "eglplatform@maybank.com.sg"
const FROM_EMAIL = "nvnaresh55@gmail.com"
const EGL_SUBJECT = "REQUEST APPROVAL EGL CODE MAP"
const COMPANY_SUBJECT = "REQUEST APPROVAL COMPAMY CODE MAP"
const UNIT_SUBJECT = "REQUEST APPROVAL UNIT CODE MAP"
const OTP_SUB = "EGL SYSTEM OTP VERIFICATION"
const SYSTEM_ERROR= "EGL PLATFORM -  User Account is Locked – INFO"
const USER_SUBJECT = "REQUEST APPROVAL USER"


module.exports = { FROM_EMAIL, EGL_SUBJECT, COMPANY_SUBJECT, UNIT_SUBJECT, OTP_SUB, SYSTEM_ERROR, USER_SUBJECT };