const usersInt={
    USER_ID: '  ',
    PASSWORD: '  ',
    FIRST_NAME: '  ',
    LAST_NAME: '  ',
    EMAIL_ID: '  ',
    CREATED_BY: '  ',
    UPDATED_BY: '  ',
    IS_ENABLED: '  ',
    LOGIN_FLG: '  ',
    UPDT_DTE: '  ',
    UPDT_PRG: '  ',
    UPDT_USR: '  ',
    END_DTE: '  ',
    INVLD_CNT: '  ',
    RESET_FLG: '  ',
    START_DATE: '  ',
    CREATED_DATE: '  ',
    LAST_MAINTAINED_DATE: '  ',
    DESIGNATION: '  ',
    DIV_DEPT_UNIT: '  ',
    DELETE_FLAG: '  ',
    EXCLUDE_DORMANT_CHECK: '  ',
    LAST_LOGIN: '  ',
    USER_TYPE: '  ',
    USER_WORK_FLOW_ID: '  ',
    MAKER_USER_ID: '  ',
    APPROVER_USER_ID: '  ',
    ACTION_COMMENTS: '  ',
    ACTION_HISTORY: '  ',
    ACTION_STATUS: '  ',
    ACTION_TS: '  ',
    IS_CURRENT: '  ',
    AUDIT_ID: '  '
}
const usersAudit = {
    USER_ID: '  ',
    PASSWORD: '  ',
    FIRST_NAME: '  ',
    LAST_NAME: '  ',
    EMAIL_ID: '  ',
    CREATED_BY: '  ',
    UPDATED_BY: '  ',
    IS_ENABLED: '  ',
    LOGIN_FLG: '  ',
    UPDT_DTE: '  ',
    UPDT_PRG: '  ',
    END_DTE: '  ',
    INVLD_CNT: '  ',
    RESET_FLG: '  ',
    START_DATE: '  ',
    CREATED_DATE: '  ',
    LAST_MAINTAINED_DATE: '  ',
    DESIGNATION: '  ',
    DIV_DEPT_UNIT: '  ',
    DELETE_FLAG: '  ',
    LAST_LOGIN: '  ',
    USER_TYPE: '  ',
    STAGE: '  ',
    AUD_ID: '  ',
    EXCLUDE_DORMANT_CHECK: '  ',
    USER_WORK_FLOW_ID: '  ',
    ACTION_COMMENTS: '  '
}

module.exports={usersInt,usersAudit}